core/urls.py
from django.urls import path

from core import views

app_name = "core"


urlpatterns = [

    ##URLS TAREAS
        path('', views.ListTarea.as_view(), name="List_Tarea"),
    path('core/list/Tarea/', views.ListTarea.as_view(), name="list_Tarea"),
    path('core/new/Tarea/', views.NewTarea.as_view(), name="create_Tarea"),
    path('core/detail/Tarea/<int:pk>/', views.DetailTarea.as_view(), name="detail_Tarea"),
    path('core/update/Tarea/<int:pk>/', views.UpdateTarea.as_view(), name="update_Tarea"),
    path('core/delete/Tarea/<int:pk>/', views.DeleteTarea.as_view(), name="delete_Tarea"),


    ##URLS PROYECTOS
    path('core/list/proyecto/', views.ListProyecto.as_view(), name="list_Proyecto"),
    path('core/new/proyecto/', views.NewProyecto.as_view(), name="create_Proyecto"),
    path('core/detail/proyecto/<int:pk>/', views.DetailProyecto.as_view(), name="detail_Proyecto"),
    path('core/update/proyecto/<int:pk>/', views.UpdateProyecto.as_view(), name="update_Proyecto"),
    path('core/delete/proyecto/<int:pk>/', views.DeleteProyecto.as_view(), name="delete_Proyecto"),


]

pem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('core/', include("core.urls")),
  

]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta

PRIORIDAD = (
    ("URGENTE", "URG"),
    ("PENDIENTE", "NEC"),
    ("ASIGNADO", "ASIG"),
)

ESTADO = (
    ("NOT STARTED", "NS"),
    ("DOING", "DG"),
    ("DONE", "DN"),
)

class Proyecto(models.Model):
    nombre = models.CharField(max_length=64, default="PROYECTO 1")
    descripcion = models.CharField(max_length=128, default="Descripción del proyecto")
    fecha_inicio = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.nombre

class Tarea(models.Model):
    Tareanombre = models.CharField(max_length=64, default="TAREA 1")
    descripcion = models.CharField(max_length=128, default="Descripción de la tarea")
    Usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    Proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE, related_name='tareas')
    timestamp = models.DateField(auto_now_add=True)
    dias_duracion = models.IntegerField(default=7)
    fecha_final = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    progreso = models.FloatField(default=0.0)
    prioridad = models.CharField(max_length=16, choices=PRIORIDAD)
    estado = models.CharField(max_length=16, choices=ESTADO)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.Tareanombre

core/forms.py
from django import forms
from .models import Tarea, Proyecto

class CreateTareaForm(forms.ModelForm):
    class Meta:
        model = Tarea
        fields = [
            "Tareanombre",
            "descripcion",
            "Usuario",
            "Proyecto",
            "dias_duracion",
            "progreso",
            "prioridad",
            "estado",
            "status"
        ]
        widgets = {
            "Tareanombre": forms.TextInput(attrs={"class":"form-control", "placeholder":"Nombre de la Tarea"}),
            "descripcion": forms.Textarea(attrs={"class":"form-control", "placeholder":"Descripción"}),
            "Usuario": forms.Select(attrs={"class":"form-control"}),
            "Proyecto": forms.Select(attrs={"class":"form-control"}),
            "dias_duracion": forms.NumberInput(attrs={"class":"form-control"}),
            "progreso": forms.NumberInput(attrs={"class":"form-control"}),
            "prioridad": forms.Select(attrs={"class":"form-control"}),
            "estado": forms.Select(attrs={"class":"form-control"}),
            "status": forms.CheckboxInput(attrs={"class":"form-check-input"})
        }

class UpdateTareaForm(forms.ModelForm):
    class Meta:
        model = Tarea
        fields = [
            "Tareanombre",
            "descripcion",
            "Usuario",
            "Proyecto",
            "dias_duracion",
            "progreso",
            "prioridad",
            "estado",
            "status"
        ]
        widgets = {
            "Tareanombre": forms.TextInput(attrs={"class":"form-control", "placeholder":"Nombre de la Tarea"}),
            "descripcion": forms.Textarea(attrs={"class":"form-control", "placeholder":"Descripción"}),
            "Usuario": forms.Select(attrs={"class":"form-control"}),
            "Proyecto": forms.Select(attrs={"class":"form-control"}),
            "dias_duracion": forms.NumberInput(attrs={"class":"form-control"}),
            "progreso": forms.NumberInput(attrs={"class":"form-control"}),
            "prioridad": forms.Select(attrs={"class":"form-control"}),
            "estado": forms.Select(attrs={"class":"form-control"}),
            "status": forms.CheckboxInput(attrs={"class":"form-check-input"})
        }

class CreateProyectoForm(forms.ModelForm):
    class Meta:
        model = Proyecto
        fields = [
            "nombre",
            "descripcion"

        ]
        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Nombre del proyecto"}),
            "descripcion": forms.Textarea(attrs={"rows": 3, "type": "text", "class": "form-control", "placeholder": "Descripción del proyecto"})
        }

class UpdateProyectoForm(forms.ModelForm):
    class Meta:
        model = Proyecto
        fields = [
            "nombre",
            "descripcion"
        ]
        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Nombre del proyecto"}),
            "descripcion": forms.Textarea(attrs={"rows": 3, "type": "text", "class": "form-control", "placeholder": "Descripción del proyecto"})
        }

core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from core import models
from core import forms 

# Create your views here.


##TAREAS CRUD

### CREATE
class NewTarea(generic.CreateView):
    template_name = "core/create_Tarea.html"
    model = models.Tarea
    form_class = forms.CreateTareaForm
    success_url = reverse_lazy("core:list_Tarea")

## List
class ListTarea(generic.View):
    template_name = "core/list_Tarea.html"
    context = {}

    def get(self, request):
        self.context = {
            "Tarea": models.Tarea.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)
    
## Detail
class DetailTarea(generic.View):
    template_name = "core/detail_Tarea.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "Tarea": models.Tarea.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)

### UPDATE
class UpdateTarea(generic.UpdateView):
    template_name = "core/update_Tarea.html"
    model = models.Tarea
    form_class = forms.UpdateTareaForm
    success_url = reverse_lazy("core:list_Tarea")


### DELETE
class DeleteTarea(generic.DeleteView):
    template_name = "core/delete_Tarea.html"
    model = models.Tarea
    success_url = reverse_lazy("core:list_Tarea")


##PROYECTOS CRUD


### CREATE
class NewProyecto(generic.CreateView):
    template_name = "core/create_Proyecto.html"
    model = models.Proyecto
    form_class = forms.CreateProyectoForm
    success_url = reverse_lazy("core:list_Proyecto")

### LIST
class ListProyecto(generic.View):
    template_name = "core/list_Proyecto.html"
    context = {}

    def get(self, request):
        self.context = {
            "proyecto": models.Proyecto.objects.all()
        }
        return render(request, self.template_name, self.context)
    
### DETAIL
class DetailProyecto(generic.View):
    template_name = "core/detail_Proyecto.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "proyecto": models.Proyecto.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)

### UPDATE
class UpdateProyecto(generic.UpdateView):
    template_name = "core/update_Proyecto.html"
    model = models.Proyecto
    form_class = forms.UpdateProyectoForm
    success_url = reverse_lazy("core:list_Proyecto")

### DELETE
class DeleteProyecto(generic.DeleteView):
    template_name = "core/delete_Proyecto.html"
    model = models.Proyecto
    success_url = reverse_lazy("core:list_Proyecto")

templates/core/create_Proyecto.html
{% extends "base/base.html" %}

{% block title %}NEW PROJECT VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-success form-control">New Project</button>
            <br>
            <a href="{% url 'core:list_Proyecto' %}" class="btn btn-danger form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/create_Tarea.html
{% extends "base/base.html" %}

{% block title %}NEW TAREA VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-success form-control">New Task</button>
            <br>
            <a href="{% url 'core:list_Tarea' %}" class="btn btn-danger form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/delete_Proyecto.html
{% extends "base/base.html" %}

{% block title %}DELETE PROJECT VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h3>¿Realmente deseas eliminar este proyecto: "{{ object }}"?</h3>
            
            <button type="submit" class="btn btn-success">Borrar Proyecto</button>
            <a href="{% url 'core:list_Proyecto' %}" class="btn btn-danger">Cancelar</a>
    </form>
{% endblock content %}

templates/core/delete_Tarea.html
{% extends "base/base.html" %}

{% block title %}DELETE TAREA VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h3>¿Realmente deseas eliminar esta Tarea: "{{ object }}"?</h3>
            
            <button type="submit" class="btn btn-success">Borrar Tarea</button>
            <a href="{% url 'core:list_Tarea' %}" class="btn btn-danger">Cancelar</a>
    </form>
{% endblock content %}

templates/core/detail_Proyecto.html
{% extends "base/base.html" %}

{% block title %}Detalle de Proyecto{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="card-title">Nombre del Proyecto</h5>
                </div>
                <div class="card-body">
                    <p class="card-text"><strong>{{ proyecto.nombre }}</strong></p>
                </div>
            </div>
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="card-title">Descripción</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ proyecto.descripcion }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="card-title">Fecha de Inicio</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ proyecto.fecha_inicio }}</p>
                </div>
            </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <a href="{% url 'core:list_Proyecto' %}" class="btn btn-primary">Regresar</a>
        </div>
    </div>
</div>
{% endblock content %}

templates/core/detail_Tarea.html
{% extends "base/base.html" %}

{% block title %}Detalle de Tarea{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="card-title">Nombre de la Tarea</h5>
                </div>
                <div class="card-body">
                    <p class="card-text"><strong>{{ Tarea.Tareanombre }}</strong></p>
                </div>
            </div>
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="card-title">Descripción</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ Tarea.descripcion }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="card-title">Progreso</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ Tarea.progreso }}%</p>
                </div>
            </div>
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="card-title">Estado</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ Tarea.estado }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="card-title">Fecha de Creación</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ Tarea.timestamp }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="card-title">Duración (Días)</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ Tarea.dias_duracion }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <a href="{% url 'core:list_Tarea' %}" class="btn btn-primary">Regresar</a>
        </div>
    </div>
</div>
{% endblock content %}

templates/core/list_Proyecto.html
{% extends "base/base.html" %}

{% block title %}LIST TASK VIEW{% endblock title %}

{% block content %}
   
   <center><h1>Proyectos</h1></center>
   <br>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>PROYECTO</th>
                <th>FECHA DE CREACIÓN</th>
                <th></th>
                <th>ACCIONES</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for p in proyecto %}
                <tr>
                    <td>{{ p.id }}</td>
                    <td>{{ p.nombre }}</td>
                    <!-- <td>{{ p.Usuario }}</td> -->
                    <td>{{ p.fecha_inicio }}</td>
                    <td><a href="{% url 'core:detail_Proyecto' p.pk %}" class="btn btn-secondary">Detalle</a></td>
                    <td><a href="{% url 'core:update_Proyecto' p.pk %}" class="btn btn-primary">Actualizar</a></td>
                    <td><a href="{% url 'core:delete_Proyecto' p.pk %}" class="btn btn-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'core:create_Proyecto' %}" class="btn btn-outline-success form-control">Nuevo Proyecto</a>
{% endblock content %}

templates/core/list_Tarea.html
{% extends "base/base.html" %}

{% block title %}LIST TASK VIEW{% endblock title %}

{% block content %}
   
   <center><h1>Tareas</h1></center>
   <br>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>NOMBRE</th>
                <th>USUARIO</th>
                <th>PROYECTO</th>
                <th>FECHA DE CREACIÓN</th>
                <th></th>
                <th>ACCIONES</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for tarea in Tarea %}
                <tr>
                    <td>{{ tarea.id }}</td>
                    <td>{{ tarea.Tareanombre }}</td>
                    <td>{{ tarea.Usuario }}</td>
                    <td>{{ tarea.Proyecto }}</td>
                    <td>{{ tarea.timestamp }}</td>
                    <td><a href="{% url 'core:detail_Tarea' tarea.pk %}" class="btn btn-secondary">Detalle</a></td>
                    <td><a href="{% url 'core:update_Tarea' tarea.pk %}" class="btn btn-primary">Actualizar</a></td>
                    <td><a href="{% url 'core:delete_Tarea' tarea.pk %}" class="btn btn-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'core:create_Tarea' %}" class="btn btn-outline-success form-control">Nueva Tarea</a>
{% endblock content %}

templates/core/update_Proyecto.html
{% extends "base/base.html" %}

{% block title %}UPDATE PROJECT VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-primary form-control">Update POYECTO</button>
            <br>
            <a href="{% url 'core:list_Proyecto' %}" class="btn btn-danger form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/update_Tarea.html
{% extends "base/base.html" %}

{% block title %}UPDATE Tarea VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-primary form-control">Update Tarea</button>
            <br>
            <a href="{% url 'core:list_Tarea' %}" class="btn btn-danger form-control">Cancel</a>
    </form>
{% endblock content %}